import { jsPDF } from "jspdf"

/**
 * Generate a PDF buffer from assessment data
 * This is a server-side function that doesn't rely on DOM elements
 */
export async function generatePdfBuffer(
  data: any,
  userName?: string,
  assessmentDate: Date = new Date(),
): Promise<Buffer> {
  // Format date and time for display
  const formattedDate = assessmentDate.toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })

  const formattedTime = assessmentDate.toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  })

  // Create PDF
  const pdf = new jsPDF({
    orientation: "portrait",
    unit: "mm",
  })

  // Set font
  pdf.setFont("helvetica")

  // Add title
  pdf.setFontSize(20)
  pdf.setTextColor(0, 0, 0)
  pdf.text("Health Assessment Results", 20, 20)

  // Add patient name if available
  pdf.setFontSize(12)
  pdf.setTextColor(0, 0, 0)
  pdf.text(`Patient: ${userName || "Anonymous User"}`, 20, 30)

  // Add date and time
  pdf.setFontSize(10)
  pdf.setTextColor(100, 100, 100)
  pdf.text(`Generated on ${formattedDate} at ${formattedTime}`, 20, 35)

  // Add risk level
  pdf.setFontSize(16)
  pdf.setTextColor(0, 0, 0)
  const riskLevel = data.result.risk.charAt(0).toUpperCase() + data.result.risk.slice(1)
  pdf.text(`Risk Level: ${riskLevel}`, 20, 45)

  // Add risk score
  pdf.setFontSize(14)
  pdf.text(`Risk Score: ${data.result.score}%`, 20, 55)

  // Add health metrics section
  pdf.setFontSize(16)
  pdf.text("Health Metrics", 20, 70)

  // Draw a line
  pdf.setDrawColor(200, 200, 200)
  pdf.line(20, 72, 190, 72)

  // Add metrics
  pdf.setFontSize(12)
  let y = 80

  // Helper function to add a metric
  const addMetric = (label: string, value: string) => {
    pdf.setTextColor(80, 80, 80)
    pdf.text(label, 20, y)
    pdf.setTextColor(0, 0, 0)
    pdf.text(value, 80, y)
    y += 10
  }

  // Basic Health Metrics
  addMetric("Age:", `${data.age} years`)
  addMetric("Gender:", data.sex === "1" ? "Male" : "Female")
  addMetric("Blood Pressure:", `${data.trestbps} mm Hg`)
  addMetric("Cholesterol:", `${data.chol} mg/dl`)

  // Chest Pain and Related Metrics
  addMetric(
    "Chest Pain Type:",
    (() => {
      const types = ["Typical angina", "Atypical angina", "Non-anginal pain", "Asymptomatic"]
      return types[Number.parseInt(data.cp)] || data.cp
    })(),
  )
  addMetric("Fasting Blood Sugar:", data.fbs === "1" ? "Above 120 mg/dl" : "Below 120 mg/dl")
  addMetric(
    "Resting ECG:",
    (() => {
      const types = ["Normal", "ST-T wave abnormality", "Left ventricular hypertrophy"]
      return types[Number.parseInt(data.restecg)] || data.restecg
    })(),
  )

  // Heart Rate and Exercise Metrics
  if (data.thalach) {
    addMetric("Max Heart Rate:", data.thalach)
  }
  addMetric("Exercise Induced Angina:", data.exang === "1" ? "Yes" : "No")

  // ST Depression and Slope
  if (data.oldpeak) {
    addMetric("ST Depression:", data.oldpeak)
  }
  if (data.slope) {
    const slopeValues = ["Upsloping", "Flat", "Downsloping"]
    addMetric("ST Slope:", slopeValues[Number.parseInt(data.slope)] || data.slope)
  }

  // Vessels and Thalassemia
  if (data.ca) {
    addMetric("Number of Major Vessels:", data.ca)
  }
  if (data.thal) {
    const thalValues = ["Normal", "Fixed defect", "Reversible defect"]
    addMetric("Thalassemia:", thalValues[Number.parseInt(data.thal)] || data.thal)
  }

  // Lifestyle Factors
  y += 5
  pdf.setFontSize(16)
  pdf.setTextColor(0, 0, 0)
  pdf.text("Lifestyle Factors", 20, y)
  y += 5

  // Draw a line
  pdf.setDrawColor(200, 200, 200)
  pdf.line(20, y, 190, y)
  y += 10

  pdf.setFontSize(12)

  // Add lifestyle metrics
  if (data.foodHabits) {
    const foodHabitsText =
      data.foodHabits === "vegetarian"
        ? "Vegetarian"
        : data.foodHabits === "non-vegetarian"
          ? "Non-Vegetarian"
          : "Mixed Diet"
    addMetric("Food Habits:", foodHabitsText)
  }

  if (data.junkFoodConsumption) {
    const junkFoodText =
      data.junkFoodConsumption === "low"
        ? "Low (rarely)"
        : data.junkFoodConsumption === "moderate"
          ? "Moderate (weekly)"
          : "High (daily)"
    addMetric("Junk Food Consumption:", junkFoodText)
  }

  if (data.sleepingHours) {
    addMetric("Sleeping Hours:", `${data.sleepingHours} hours/day`)
  }

  // Add disclaimer
  y += 10
  pdf.setFontSize(10)
  pdf.setTextColor(100, 100, 100)
  pdf.text("This assessment is not a medical diagnosis. Please consult with a healthcare provider.", 20, y)

  // Add footer
  pdf.setFontSize(8)
  pdf.setTextColor(150, 150, 150)
  pdf.text(`Generated by HeartPredict on ${formattedDate} at ${formattedTime}`, 20, pdf.internal.pageSize.height - 10)

  // Convert to buffer
  const pdfOutput = pdf.output("arraybuffer")
  return Buffer.from(pdfOutput)
}
